export interface TargetInfo {
  id: string;
  name: string;
  emoji: string;
  fact: string;
  distance: string; // average distance or live calculated
  color: string; // hsl color for badge/dot
  category: "qibla" | "solar" | "star" | "landmark" | "constellation" | "deepspace" | "satellite" | "comet";
  categoryLabel: string;
  /** Fixed coordinates if it is an Earth Landmark */
  coords?: { lat: number; lng: number };
  /** Fixed RA/Dec if it is a Star */
  raDec?: { ra: number; dec: number };
  /** Extended detail fields */
  diameter: string;
  orbitalPeriod: string;
  rotationPeriod: string;
  moons: number;
  surfaceTemp: string;
  type: string;
  description: string;
}

export type PlanetInfo = TargetInfo; // Alias for backward compatibility

export const ALL_TARGETS_INFO: TargetInfo = {
  id: "all",
  name: "All Targets (A to Z Sky View)",
  emoji: "🌌",
  fact: "Simultaneously view all planets, stars, Kaaba (Qibla), and landmarks in one AR screen",
  distance: "Universal View",
  color: "hsl(280, 100%, 70%)",
  category: "landmark",
  categoryLabel: "All-in-One Mode",
  diameter: "All Targets",
  orbitalPeriod: "N/A",
  rotationPeriod: "N/A",
  moons: 0,
  surfaceTemp: "N/A",
  type: "Simultaneous Multi-Target AR Tracker",
  description: "Displays all solar planets, sacred landmarks, bright stars, and world wonders simultaneously in your AR camera viewport!"
};

export const TARGETS: TargetInfo[] = [
  // --- SACRED & RELIGIOUS LANDMARKS ---
  {
    id: "kaaba",
    name: "Kaaba (Qibla)",
    emoji: "🕋",
    fact: "The sacred direction of prayer (Qibla) for Muslims worldwide in Mecca",
    distance: "Calculated Live",
    color: "hsl(48, 95%, 55%)",
    category: "qibla",
    categoryLabel: "Sacred & Qibla",
    coords: { lat: 21.422487, lng: 39.826206 },
    diameter: "13.1m x 11.03m x 12.86m",
    orbitalPeriod: "N/A (Fixed Geodetic Location)",
    rotationPeriod: "24 hours (Earth Rotation)",
    moons: 0,
    surfaceTemp: "~30°C (Mecca)",
    type: "Sacred Landmark (Mecca, Saudi Arabia)",
    description:
      "The Kaaba (🕋) is the cubic building at the heart of Masjid al-Haram in Mecca, Saudi Arabia. It is the holiest sanctuary in Islam and the universal orientation for daily prayers worldwide.",
  },
  {
    id: "nabawi",
    name: "Al-Masjid an-Nabawi",
    emoji: "🕌",
    fact: "The Prophet's Mosque in Madinah, featuring the Green Dome",
    distance: "Calculated Live",
    color: "hsl(145, 75%, 45%)",
    category: "qibla",
    categoryLabel: "Sacred & Qibla",
    coords: { lat: 24.4672, lng: 39.6112 },
    diameter: "Land Area: ~384,000 m²",
    orbitalPeriod: "N/A (Fixed Geodetic Location)",
    rotationPeriod: "24 hours (Earth Rotation)",
    moons: 0,
    surfaceTemp: "~32°C (Madinah)",
    type: "Sacred Sanctuary (Madinah)",
    description:
      "Al-Masjid an-Nabawi (The Prophet's Mosque) is the second holiest site in Islam, built originally by the Prophet Muhammad in Madinah.",
  },
  {
    id: "alaqsa",
    name: "Al-Aqsa Mosque",
    emoji: "🕌",
    fact: "The third holiest site in Islam located in the Old City of Jerusalem",
    distance: "Calculated Live",
    color: "hsl(40, 90%, 50%)",
    category: "qibla",
    categoryLabel: "Sacred & Qibla",
    coords: { lat: 31.7761, lng: 35.2358 },
    diameter: "Land Area: ~144,000 m²",
    orbitalPeriod: "N/A (Fixed Geodetic Location)",
    rotationPeriod: "24 hours (Earth Rotation)",
    moons: 0,
    surfaceTemp: "~22°C (Jerusalem)",
    type: "Sacred Sanctuary (Jerusalem)",
    description:
      "Al-Aqsa Mosque is an ancient holy compound in Jerusalem, recognized as the first Qibla in Islamic history.",
  },

  // --- SOLAR SYSTEM PLANETS (A to Z) ---
  {
    id: "jupiter",
    name: "Jupiter",
    emoji: "🟠",
    fact: "Jupiter's Great Red Spot is a storm bigger than Earth",
    distance: "778M km",
    color: "hsl(25, 60%, 55%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "139,820 km",
    orbitalPeriod: "11.9 years",
    rotationPeriod: "9h 56m",
    moons: 95,
    surfaceTemp: "-108°C",
    type: "Gas giant",
    description:
      "Jupiter is the largest planet in our solar system — more than twice as massive as all other planets combined.",
  },
  {
    id: "mars",
    name: "Mars",
    emoji: "🔴",
    fact: "Home to Olympus Mons, the tallest volcano in the solar system",
    distance: "225M km",
    color: "hsl(10, 70%, 50%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "6,779 km",
    orbitalPeriod: "687 days",
    rotationPeriod: "24h 37m",
    moons: 2,
    surfaceTemp: "-87°C to -5°C",
    type: "Terrestrial planet",
    description:
      "Mars is known as the Red Planet due to iron oxide on its surface. It features ancient river valleys and giant volcanoes.",
  },
  {
    id: "mercury",
    name: "Mercury",
    emoji: "🪨",
    fact: "A year on Mercury is just 88 Earth days",
    distance: "77M km",
    color: "hsl(30, 30%, 55%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "4,879 km",
    orbitalPeriod: "88 days",
    rotationPeriod: "59 days",
    moons: 0,
    surfaceTemp: "-180°C to 430°C",
    type: "Terrestrial planet",
    description:
      "Mercury is the smallest planet and closest to the Sun. It experiences extreme temperature swings between day and night.",
  },
  {
    id: "moon",
    name: "Moon",
    emoji: "🌙",
    fact: "The only celestial body humans have walked on",
    distance: "384,400 km",
    color: "hsl(210, 15%, 80%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "3,474 km",
    orbitalPeriod: "27.3 days",
    rotationPeriod: "27.3 days",
    moons: 0,
    surfaceTemp: "-173°C to 127°C",
    type: "Natural satellite",
    description:
      "Earth's natural satellite, responsible for ocean tides and stabilizing Earth's axial rotation.",
  },
  {
    id: "neptune",
    name: "Neptune",
    emoji: "💙",
    fact: "Neptune has the strongest winds in the solar system (up to 2,100 km/h)",
    distance: "4.5B km",
    color: "hsl(220, 70%, 55%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "49,244 km",
    orbitalPeriod: "165 years",
    rotationPeriod: "16h 6m",
    moons: 16,
    surfaceTemp: "-201°C",
    type: "Ice giant",
    description:
      "Neptune is the furthest planet from the Sun, exhibiting deep blue atmospheric methane clouds and extreme storms.",
  },
  {
    id: "pluto",
    name: "Pluto",
    emoji: "❄️",
    fact: "Pluto has a heart-shaped glacier named Tombaugh Regio",
    distance: "5.9B km",
    color: "hsl(200, 30%, 65%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "2,376 km",
    orbitalPeriod: "248 years",
    rotationPeriod: "6.4 days",
    moons: 5,
    surfaceTemp: "-229°C",
    type: "Dwarf planet",
    description:
      "Pluto is a dwarf planet in the Kuiper belt, discovered in 1930 and visited by NASA's New Horizons spacecraft in 2015.",
  },
  {
    id: "saturn",
    name: "Saturn",
    emoji: "🪐",
    fact: "Saturn's rings are made mostly of ice particles and space dust",
    distance: "1.4B km",
    color: "hsl(45, 50%, 60%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "116,460 km",
    orbitalPeriod: "29.5 years",
    rotationPeriod: "10h 42m",
    moons: 146,
    surfaceTemp: "-138°C",
    type: "Gas giant",
    description:
      "Saturn is renowned for its vast ring system and its giant moon Titan, which possesses a dense atmosphere.",
  },
  {
    id: "sun",
    name: "Sun",
    emoji: "☀️",
    fact: "Light takes 8 minutes to reach Earth from the Sun",
    distance: "149.6M km",
    color: "hsl(45, 100%, 66%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "1,392,700 km",
    orbitalPeriod: "N/A (Center of Solar System)",
    rotationPeriod: "~25 days",
    moons: 0,
    surfaceTemp: "5,500°C",
    type: "G-type star",
    description:
      "The central star of our solar system, powering life on Earth through nuclear fusion at its core.",
  },
  {
    id: "uranus",
    name: "Uranus",
    emoji: "🔵",
    fact: "Uranus rotates on its side like a rolling bowling ball",
    distance: "2.9B km",
    color: "hsl(185, 60%, 60%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "50,724 km",
    orbitalPeriod: "84 years",
    rotationPeriod: "17h 14m",
    moons: 28,
    surfaceTemp: "-195°C",
    type: "Ice giant",
    description:
      "Uranus has an extreme tilt of 98 degrees, resulting in 42-year long polar nights and days.",
  },
  {
    id: "venus",
    name: "Venus",
    emoji: "🌟",
    fact: "Venus is the hottest planet in the solar system at 465°C",
    distance: "261M km",
    color: "hsl(40, 80%, 70%)",
    category: "solar",
    categoryLabel: "Solar System",
    diameter: "12,104 km",
    orbitalPeriod: "225 days",
    rotationPeriod: "243 days",
    moons: 0,
    surfaceTemp: "465°C",
    type: "Terrestrial planet",
    description:
      "Venus is wrapped in dense clouds of sulfuric acid and carbon dioxide, producing an extreme greenhouse effect.",
  },

  // --- STARS & SPACE (A to Z) ---
  {
    id: "alpha-centauri",
    name: "Alpha Centauri",
    emoji: "✨",
    fact: "The closest star system to our Solar System at 4.37 light years",
    distance: "4.37 Light Years",
    color: "hsl(50, 90%, 70%)",
    category: "star",
    categoryLabel: "Stars & Space",
    raDec: { ra: 219.9, dec: -60.8 },
    diameter: "1,700,000 km",
    orbitalPeriod: "79.9 years",
    rotationPeriod: "22 days",
    moons: 0,
    surfaceTemp: "5,519°C",
    type: "Triple Star System",
    description:
      "Alpha Centauri is a triple star system consisting of Rigil Kentaurus, Toliman, and Proxima Centauri.",
  },
  {
    id: "betelgeuse",
    name: "Betelgeuse",
    emoji: "🌟",
    fact: "A red supergiant star in Orion so large it would engulf Jupiter's orbit",
    distance: "642 Light Years",
    color: "hsl(15, 90%, 60%)",
    category: "star",
    categoryLabel: "Stars & Space",
    raDec: { ra: 88.8, dec: 7.4 },
    diameter: "1,200,000,000 km",
    orbitalPeriod: "N/A",
    rotationPeriod: "~36 years",
    moons: 0,
    surfaceTemp: "3,200°C",
    type: "Red Supergiant",
    description:
      "Betelgeuse is a prominent star in the constellation Orion, approaching the end of its life as a future supernova.",
  },
  {
    id: "iss",
    name: "ISS (Space Station)",
    emoji: "🛰️",
    fact: "Orbits Earth 16 times a day at 28,000 km/h",
    distance: "408 km",
    color: "hsl(190, 80%, 65%)",
    category: "star",
    categoryLabel: "Stars & Space",
    diameter: "109 meters",
    orbitalPeriod: "92 minutes",
    rotationPeriod: "92 minutes",
    moons: 0,
    surfaceTemp: "-157°C to 121°C",
    type: "Microgravity Research Laboratory",
    description:
      "The International Space Station is a modular space station in low Earth orbit, orbiting Earth every 90 minutes.",
  },
  {
    id: "polaris",
    name: "Polaris (North Star)",
    emoji: "⭐",
    fact: "Sits almost directly above Earth's North Pole for celestial navigation",
    distance: "433 Light Years",
    color: "hsl(190, 90%, 75%)",
    category: "star",
    categoryLabel: "Stars & Space",
    raDec: { ra: 37.95, dec: 89.26 },
    diameter: "46,000,000 km",
    orbitalPeriod: "N/A",
    rotationPeriod: "~119 days",
    moons: 0,
    surfaceTemp: "5,742°C",
    type: "Yellow Supergiant Star",
    description:
      "Polaris remains fixed in the northern night sky while all other stars appear to rotate around it.",
  },
  {
    id: "sirius",
    name: "Sirius (Dog Star)",
    emoji: "💎",
    fact: "The brightest star in Earth's night sky, located in Canis Major",
    distance: "8.6 Light Years",
    color: "hsl(210, 100%, 75%)",
    category: "star",
    categoryLabel: "Stars & Space",
    raDec: { ra: 101.3, dec: -16.7 },
    diameter: "2,380,000 km",
    orbitalPeriod: "50 years (binary)",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "9,666°C",
    type: "A-type Main-Sequence Star",
    description:
      "Sirius is the brightest star visible from Earth, twice as massive as our Sun and 25 times more luminous.",
  },
  {
    id: "vega",
    name: "Vega",
    emoji: "💫",
    fact: "Was the first star other than the Sun to be photographed",
    distance: "25 Light Years",
    color: "hsl(220, 90%, 80%)",
    category: "star",
    categoryLabel: "Stars & Space",
    raDec: { ra: 279.2, dec: 38.78 },
    diameter: "3,830,000 km",
    orbitalPeriod: "N/A",
    rotationPeriod: "12.5 hours",
    moons: 0,
    surfaceTemp: "9,329°C",
    type: "Class A Star",
    description:
      "Vega is the brightest star in the northern constellation of Lyra and served as the North Pole star around 12,000 BC.",
  },

  // --- WORLD LANDMARKS (A to Z) ---
  {
    id: "burj-khalifa",
    name: "Burj Khalifa",
    emoji: "🏙️",
    fact: "The tallest artificial structure in the world at 828 meters",
    distance: "Calculated Live",
    color: "hsl(199, 90%, 60%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 25.1972, lng: 55.2744 },
    diameter: "Height: 828 meters",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~35°C (Dubai)",
    type: "Skyscraper (Dubai, UAE)",
    description:
      "Burj Khalifa in Dubai is the world's tallest building, holding multiple global architectural records.",
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    emoji: "🗼",
    fact: "Constructed in 1889 for the Paris World's Fair, standing 330 meters tall",
    distance: "Calculated Live",
    color: "hsl(35, 70%, 55%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 48.8584, lng: 2.2945 },
    diameter: "Height: 330 meters",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~18°C (Paris)",
    type: "Monument (Paris, France)",
    description:
      "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France.",
  },
  {
    id: "giza-pyramid",
    name: "Great Pyramid of Giza",
    emoji: "🏜️",
    fact: "The oldest and largest of the Seven Wonders of the Ancient World",
    distance: "Calculated Live",
    color: "hsl(40, 80%, 50%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 29.9792, lng: 31.1342 },
    diameter: "Base: 230m | Height: 138.8m",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~30°C (Giza)",
    type: "Ancient Wonder (Egypt)",
    description:
      "The Great Pyramid of Giza was built as a tomb for Pharaoh Khufu around 2560 BC.",
  },
  {
    id: "mount-everest",
    name: "Mount Everest",
    emoji: "⛰️",
    fact: "Earth's highest mountain above sea level at 8,848.86 meters",
    distance: "Calculated Live",
    color: "hsl(200, 40%, 80%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 27.9881, lng: 86.925 },
    diameter: "Elevation: 8,848.86m",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "-19°C to -36°C",
    type: "Mountain Peak (Himalayas)",
    description:
      "Mount Everest is located in the Mahalangur Himal sub-range of the Himalayas on the border of Nepal and China.",
  },
  {
    id: "statue-of-liberty",
    name: "Statue of Liberty",
    emoji: "🗽",
    fact: "A gift of friendship from the people of France to the United States in 1886",
    distance: "Calculated Live",
    color: "hsl(160, 60%, 50%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 40.6892, lng: -74.0445 },
    diameter: "Height: 93 meters",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~20°C (New York)",
    type: "National Monument (USA)",
    description:
      "The Statue of Liberty stands on Liberty Island in New York Harbor as a global icon of freedom.",
  },
  {
    id: "stonehenge",
    name: "Stonehenge",
    emoji: "🏛️",
    fact: "Prehistoric stone circle aligned with the solstice sunrises",
    distance: "Calculated Live",
    color: "hsl(90, 20%, 50%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 51.1789, lng: -1.8262 },
    diameter: "Diameter: 33 meters",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~14°C (UK)",
    type: "Prehistoric Monument (UK)",
    description:
      "Stonehenge is a ring of standing megalithic stones set within earthworks in Wiltshire, England.",
  },
  {
    id: "tokyo-tower",
    name: "Tokyo Tower",
    emoji: "⛩️",
    fact: "Communications tower inspired by the Eiffel Tower, standing 332.9 meters tall",
    distance: "Calculated Live",
    color: "hsl(5, 85%, 60%)",
    category: "landmark",
    categoryLabel: "World Wonders",
    coords: { lat: 35.6586, lng: 139.7454 },
    diameter: "Height: 332.9 meters",
    orbitalPeriod: "N/A",
    rotationPeriod: "24 hours",
    moons: 0,
    surfaceTemp: "~22°C (Tokyo)",
    type: "Landmark (Tokyo, Japan)",
    description:
      "Tokyo Tower is a communications and observation tower in the Shiba-koen district of Minato, Tokyo.",
  },

  // --- CONSTELLATIONS ---
  {
    id: "orion-constellation",
    name: "Orion Constellation",
    emoji: "🌌",
    fact: "Features Betelgeuse, Rigel, and the famous three-star Hunter's Belt",
    distance: "1,344 Light Years",
    color: "hsl(215, 90%, 65%)",
    category: "constellation",
    categoryLabel: "Constellations",
    raDec: { ra: 83.8, dec: -5.4 },
    diameter: "Span: ~25 degrees",
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Equatorial Constellation",
    description:
      "Orion is one of the most prominent and recognizable constellations in the sky, visible worldwide.",
  },
  {
    id: "ursa-major",
    name: "Ursa Major (Big Dipper)",
    emoji: "🐻",
    fact: "Contains the famous Big Dipper asterism used to find Polaris (North Star)",
    distance: "80 Light Years",
    color: "hsl(200, 85%, 65%)",
    category: "constellation",
    categoryLabel: "Constellations",
    raDec: { ra: 160.0, dec: 55.0 },
    diameter: "Span: ~30 degrees",
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Northern Constellation",
    description:
      "Ursa Major (The Great Bear) is visible throughout the year in most of the northern hemisphere.",
  },
  {
    id: "cassiopeia",
    name: "Cassiopeia",
    emoji: "👑",
    fact: "Recognizable by its distinct 'W' shape formed by 5 bright stars",
    distance: "228 Light Years",
    color: "hsl(280, 80%, 70%)",
    category: "constellation",
    categoryLabel: "Constellations",
    raDec: { ra: 15.0, dec: 60.0 },
    diameter: "Span: ~15 degrees",
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Northern Circumpolar Constellation",
    description:
      "Cassiopeia is named after the vain queen in Greek mythology, located opposite the Big Dipper.",
  },
  {
    id: "scorpius",
    name: "Scorpius",
    emoji: "🦂",
    fact: "Anchored by the brilliant red supergiant star Antares (Heart of the Scorpion)",
    distance: "550 Light Years",
    color: "hsl(15, 95%, 60%)",
    category: "constellation",
    categoryLabel: "Constellations",
    raDec: { ra: 250.0, dec: -30.0 },
    diameter: "Span: ~20 degrees",
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Zodiac Constellation",
    description:
      "Scorpius lies near the center of the Milky Way, packed with star clusters and nebulae.",
  },

  // --- DEEP SPACE NEBULAE & GALAXIES ---
  {
    id: "andromeda-galaxy",
    name: "Andromeda Galaxy (M31)",
    emoji: "🌀",
    fact: "The nearest major galaxy to the Milky Way, containing over 1 trillion stars",
    distance: "2.537 Million Light Years",
    color: "hsl(270, 90%, 75%)",
    category: "deepspace",
    categoryLabel: "Deep Space & Nebulae",
    raDec: { ra: 10.68, dec: 41.27 },
    diameter: "220,000 Light Years",
    orbitalPeriod: "Approaching Milky Way at 110 km/s",
    rotationPeriod: "225 Million years",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Barred Spiral Galaxy",
    description:
      "Andromeda is the largest galaxy in our Local Group, visible to the naked eye under dark skies.",
  },
  {
    id: "orion-nebula",
    name: "Orion Nebula (M42)",
    emoji: "🌸",
    fact: "A massive stellar nursery where thousands of new stars are currently forming",
    distance: "1,344 Light Years",
    color: "hsl(330, 85%, 65%)",
    category: "deepspace",
    categoryLabel: "Deep Space & Nebulae",
    raDec: { ra: 83.82, dec: -5.39 },
    diameter: "24 Light Years",
    orbitalPeriod: "N/A",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "10,000°C (Gas Temp)",
    type: "Diffuse Emission Nebula",
    description:
      "M42 is one of the brightest nebulae in the night sky, located south of Orion's Belt.",
  },
  {
    id: "crab-nebula",
    name: "Crab Nebula (M1)",
    emoji: "🦀",
    fact: "Supernova remnant observed by historical astronomers in the year 1054 AD",
    distance: "6,500 Light Years",
    color: "hsl(180, 80%, 60%)",
    category: "deepspace",
    categoryLabel: "Deep Space & Nebulae",
    raDec: { ra: 83.63, dec: 22.01 },
    diameter: "11 Light Years",
    orbitalPeriod: "N/A",
    rotationPeriod: "Pulsar rotates 30 times/sec",
    moons: 0,
    surfaceTemp: "N/A",
    type: "Supernova Remnant & Pulsar",
    description:
      "Powered by a rapidly spinning neutron star (pulsar) emitting intense radiation.",
  },

  // --- COMETS & SATELLITES ---
  {
    id: "halleys-comet",
    name: "Halley's Comet (1P/Halley)",
    emoji: "☄️",
    fact: "Famous periodic comet returning to Earth's vicinity every 75-76 years",
    distance: "5.2B km (Aphelion)",
    color: "hsl(190, 95%, 70%)",
    category: "comet",
    categoryLabel: "Comets & Satellites",
    raDec: { ra: 148.0, dec: 17.0 },
    diameter: "11 km x 8 km",
    orbitalPeriod: "75.3 years",
    rotationPeriod: "2.2 days",
    moons: 0,
    surfaceTemp: "-220°C to 77°C",
    type: "Periodic Comet",
    description:
      "Halley's Comet next predicted inner solar system pass will occur in mid-2061.",
  },
  {
    id: "jwst",
    name: "James Webb Telescope (JWST)",
    emoji: "🔭",
    fact: "Humanity's premier infrared space observatory orbiting the Sun-Earth L2 point",
    distance: "1.5 Million km from Earth",
    color: "hsl(45, 95%, 60%)",
    category: "satellite",
    categoryLabel: "Comets & Satellites",
    raDec: { ra: 95.0, dec: -15.0 },
    diameter: "Primary Mirror: 6.5 meters",
    orbitalPeriod: "Halo orbit around Sun-Earth L2",
    rotationPeriod: "N/A",
    moons: 0,
    surfaceTemp: "-233°C (Cryogenic Shield)",
    type: "Infrared Space Observatory",
    description:
      "JWST gazes back over 13.5 billion years of cosmic history to observe the first stars and exoplanets.",
  },
  {
    id: "hubble",
    name: "Hubble Space Telescope (HST)",
    emoji: "🛰️",
    fact: "Has taken over 1.5 million revolutionary astronomical observations since 1990",
    distance: "535 km (Low Earth Orbit)",
    color: "hsl(210, 90%, 70%)",
    category: "satellite",
    categoryLabel: "Comets & Satellites",
    diameter: "Length: 13.2 meters",
    orbitalPeriod: "95 minutes",
    rotationPeriod: "95 minutes",
    moons: 0,
    surfaceTemp: "-128°C to 93°C",
    type: "Low Earth Orbit Observatory",
    description:
      "Hubble orbits Earth every 95 minutes, capturing high-resolution deep space images.",
  }
];

export const PLANETS = TARGETS; // Export alias

export function getPlanetInfo(nameOrId: string): TargetInfo {
  if (nameOrId === "all") return ALL_TARGETS_INFO;
  const query = nameOrId.toLowerCase();
  return (
    TARGETS.find(
      (t) => t.id === query || t.name.toLowerCase() === query || t.name.toLowerCase().includes(query)
    ) || TARGETS[0]
  );
}
